// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type RelationshipStatus string

const (
	RelationshipStatusPending  RelationshipStatus = "pending"
	RelationshipStatusAccepted RelationshipStatus = "accepted"
	RelationshipStatusBlocked  RelationshipStatus = "blocked"
)

func (e *RelationshipStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RelationshipStatus(s)
	case string:
		*e = RelationshipStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RelationshipStatus: %T", src)
	}
	return nil
}

type NullRelationshipStatus struct {
	RelationshipStatus RelationshipStatus `json:"relationship_status"`
	Valid              bool               `json:"valid"` // Valid is true if RelationshipStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRelationshipStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RelationshipStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RelationshipStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRelationshipStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RelationshipStatus), nil
}

type User struct {
	ID            pgtype.UUID        `json:"id"`
	Username      string             `json:"username"`
	Email         string             `json:"email"`
	PasswordHash  pgtype.Text        `json:"password_hash"`
	OauthProvider pgtype.Text        `json:"oauth_provider"`
	DisplayName   pgtype.Text        `json:"display_name"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type UserRelationship struct {
	User1       pgtype.UUID        `json:"user1"`
	User2       pgtype.UUID        `json:"user2"`
	RequestedBy pgtype.UUID        `json:"requested_by"`
	Status      RelationshipStatus `json:"status"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
